 all: main.cpp Track.cpp Session.cpp Conference.cpp SessionOrganizer.cpp
	  g++ -std=c++11 -o main main.cpp Track.cpp Session.cpp Conference.cpp SessionOrganizer.cpp

 opt: main.cpp Track.cpp Session.cpp Conference.cpp SessionOrganizer.cpp
	  g++ -O3 -std=c++11 -o main main.cpp Track.cpp Session.cpp Conference.cpp SessionOrganizer.cpp